# Generated by Django 5.1.7 on 2025-06-12 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_historicalorderdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.CharField(choices=[('created', 'Creado'), ('updated', 'Actualizado'), ('deleted', 'Eliminado')], max_length=100)),
                ('quantity', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='products.orderdetail')),
            ],
        ),
    ]
